# generated from colcon_powershell/shell/template/prefix_chain.ps1.em

# This script extends the environment with the environment of other prefix
# paths which were sourced when this file was generated as well as all packages
# contained in this prefix path.

# function to source another script with conditional trace output
# first argument: the path of the script
function _colcon_prefix_chain_powershell_source_script {
  param (
    $_colcon_prefix_chain_powershell_source_script_param
  )
  # source script with conditional trace output
  if (Test-Path $_colcon_prefix_chain_powershell_source_script_param) {
    if ($env:COLCON_TRACE) {
      echo ". '$_colcon_prefix_chain_powershell_source_script_param'"
    }
    . "$_colcon_prefix_chain_powershell_source_script_param"
  } else {
    Write-Error "not found: '$_colcon_prefix_chain_powershell_source_script_param'"
  }
}

# source chained prefixes
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/catkin\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/genmsg\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/gencpp\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/geneus\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/genlisp\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/gennodejs\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/genpy\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/bond_core\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/cmake_modules\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/class_loader\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/common_msgs\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/common_tutorials\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/cpp_common\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/desktop\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/diagnostics\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/executive_smach\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/geometry\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/geometry_tutorials\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/gl_dependency\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/joint_state_publisher_gui\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/media_export\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/message_generation\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/message_runtime\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/mk\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/nodelet_core\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/qt_dotgraph\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/qt_gui\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/qt_gui_py_common\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/qwt_dependency\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/robot\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/ros\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/ros_base\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/ros_comm\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/ros_core\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/ros_environment\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/ros_tutorials\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/rosbag_migration_rule\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/rosbash\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/rosboost_cfg\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/rosbuild\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/rosclean\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/roscpp_core\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/roscpp_traits\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/roscreate\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/rosgraph\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/roslang\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/roslint\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/roslisp\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/rosmake\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/rosmaster\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/rospack\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/roslib\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/rosparam\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/rospy\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/rosservice\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/rostime\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/roscpp_serialization\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/python_qt_binding\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/roslaunch\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/rosunit\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/angles\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/rosconsole\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/pluginlib\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/qt_gui_cpp\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/resource_retriever\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/rosconsole_bridge\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/roslz4\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/rostest\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/rqt_action\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/rqt_bag\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/rqt_bag_plugins\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/rqt_common_plugins\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/rqt_console\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/rqt_dep\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/rqt_graph\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/rqt_gui\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/rqt_logger_level\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/rqt_moveit\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/rqt_msg\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/rqt_nav_view\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/rqt_plot\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/rqt_pose_view\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/rqt_publisher\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/rqt_py_console\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/rqt_robot_dashboard\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/rqt_robot_monitor\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/rqt_robot_plugins\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/rqt_robot_steering\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/rqt_runtime_monitor\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/rqt_service_caller\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/rqt_shell\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/rqt_srv\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/rqt_tf_tree\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/rqt_top\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/rqt_topic\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/rqt_web\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/smach\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/smclib\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/std_msgs\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/actionlib_msgs\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/bond\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/diagnostic_msgs\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/geometry_msgs\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/eigen_conversions\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/kdl_conversions\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/nav_msgs\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/rosgraph_msgs\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/rqt_py_common\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/shape_msgs\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/smach_msgs\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/std_srvs\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/tf2_msgs\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/tf2\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/trajectory_msgs\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/control_msgs\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/urdf_parser_plugin\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/visualization_msgs\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/visualization_tutorials\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/viz\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/webkit_dependency\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/xmlrpcpp\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/roscpp\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/bondcpp\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/bondpy\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/nodelet\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/nodelet_tutorial_math\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/pluginlib_tutorials\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/roscpp_tutorials\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/rosout\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/diagnostic_aggregator\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/diagnostic_updater\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/diagnostic_common_diagnostics\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/dynamic_reconfigure\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/filters\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/joint_state_publisher\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/message_filters\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/rosbag_storage\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/rosmsg\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/rosnode\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/rospy_tutorials\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/rostopic\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/rqt_gui_cpp\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/rqt_gui_py\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/rqt_reconfigure\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/self_test\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/smach_ros\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/tf2_py\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/topic_tools\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/rosbag\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/actionlib\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/actionlib_tutorials\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/diagnostic_analysis\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/nodelet_topic_tools\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/roswtf\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/rqt_launch\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/sensor_msgs\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/cv_bridge\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/image_transport\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/map_msgs\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/rqt_image_view\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/stereo_msgs\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/tf2_ros\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/tf\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/tf2_geometry_msgs\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/interactive_markers\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/interactive_marker_tutorials\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/laser_geometry\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/tf2_kdl\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/tf_conversions\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/turtlesim\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/turtle_actionlib\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/turtle_tf\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/turtle_tf2\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/urdf\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/kdl_parser\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/robot_state_publisher\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/rviz\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/librviz_tutorial\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/rqt_rviz\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/rviz_plugin_tutorials\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/rviz_python_tutorial\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/urdf_tutorial\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/visualization_marker_tutorials\local_setup.ps1"
_colcon_prefix_chain_powershell_source_script "/home/camillo/noetic_ws/devel_isolated/xacro\local_setup.ps1"

# source this prefix
$env:COLCON_CURRENT_PREFIX=(Split-Path $PSCommandPath -Parent)
_colcon_prefix_chain_powershell_source_script "$env:COLCON_CURRENT_PREFIX\local_setup.ps1"
